version: "3.9"

services:
  sshd-local:
    build: .
    ports:
      - 2222:22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./authorized_keys:/home/dev/.ssh/authorized_keys
